version: '3.8'

services:
  personal-assistant:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai-personal-assistant
    volumes:
      - ./credentials.json:/app/credentials.json:ro
      - ./token.json:/app/token.json
      - ./db:/app/db
      - ./.env:/app/.env:ro
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - "127.0.0.1:8080:8080"  # Port for OAuth callback
    healthcheck:
      test: ["CMD", "python", "-c", "import os; exit(0 if os.path.exists('/app/db/checkpoints.sqlite') else 1)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    networks:
      - assistant-network

  # Uncomment to add a WhatsApp API service
  # whatsapp-api:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: ai-whatsapp-api
  #   command: ["python", "app_whatsapp.py"]
  #   volumes:
  #     - ./credentials.json:/app/credentials.json:ro
  #     - ./token.json:/app/token.json
  #     - ./db:/app/db
  #     - ./.env:/app/.env:ro
  #   env_file:
  #     - .env
  #   ports:
  #     - "127.0.0.1:8000:8000"  # WhatsApp API port
  #   restart: unless-stopped
  #   depends_on:
  #     - personal-assistant
  #   networks:
  #     - assistant-network

networks:
  assistant-network:
    driver: bridge 